### ISSUE TITLE
Should register_template return offset relative to center pixel?

### ISSUE THREAD

**Issue by cmeyer** [nion-software/niondata#18]
```
quality, offset = xd.register_template(img, tmpl_img)
offset = Geometry.FloatPoint(y=img.data_shape[0] * 0.5 - offset[0], x=img.data_shape[1] * 0.5 - offset[1])
```

**Comment by Brow71189** [comment]
I think you're right. As a high level function it should return the offset relative to the center pixel.
Would you prefer that it returns a `Geometry.FloatPoint` object over a simple tuple of co-ordinates?

**Comment by cmeyer** [comment]
To be consistent, let's stick with a tuple for now; but my intention is to switch `niondata` to use the `Geometry` functions at some point.

**Comment by Brow71189** [comment]
Alright then I'll make the change.
