### ISSUE TITLE
function_concatenate should preserve data_descriptor of input data

### ISSUE THREAD

**Issue by Brow71189** [nion-software/niondata#6]
The current implementation uses the default data_descriptor from DataAndMetadata for the result of concatenate. This can lead to unexpected result when concatenating e.g. two sequences, because the result would then be a collection (which is the default behavior of DataAndMetadata).
To decide which data_descriptor to use there are two options:
1. Use the data_descriptor of the first input xdata. This would match the current behavior for intensity_calibration

2. Only allow concatenation of xdata with homogeneous data_descriptors and use the common data_descriptor.

The second method would be "cleaner" but is also more restrictive and could cause some confusion for users. On the other hand, concatenating non-homogeneous data is not a well-defined operation so it should maybe not be allowed.

**Comment by cmeyer** [comment]
Is this closed with this commit 422c897b7a2295ad907b7beaef73dcae5a2ca520 ?

**Comment by Brow71189** [comment]
I didn't see that there was an open issue but I believe the commit closes
it.

Chris Meyer <notifications@github.com> schrieb am Mo., 4. Mai 2020, 18:14:
